version: 0.0
os: linux
files:
  - source: /files/
    destination: /opt/
hooks:
  BeforeInstall:
    - location: /scripts/removeFiles
      timeout: 300
      runas: root
  AfterInstall:
    - location: /scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: /scripts/stop_server
      timeout: 300
      runas: root

