version: 0.0
os: linux
files:
  - source: /
    destination: /opt/
hooks:
  BeforeInstall:
    - location: /removeFiles
      timeout: 300
      runas: root
  AfterInstall:
    - location: /start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: /stop_server
      timeout: 300
      runas: root

