version: 0.2
phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y
      - apt-get install -y openjdk-8-jdk
      - apt-get install -y maven
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - java -version
      - mvn --version
      - docker --version
      - $(aws ecr get-login --no-include-email --region us-west-2)
  build:
    commands:
      - mvn clean install
      - docker build -t  movieflix .
artifacts:
  files:
    - appspec.yml
    - Dockerfile
    - removeFiles
    - start_server
    - stop_server
    - start_up.sh
    - Movieflix.jar