version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - sudo docker images
      - $(aws ecr get-login --no-include-email --region us-west-2)
  build:
    commands:
      - mvn clean install
      - docker build -t  movieflix .
artifacts:
  files:
    - appspec.yml
    - Dockerfile
    - removeFiles
    - start_server
    - stop_server
    - start_up.sh
    - Movieflix.jar