version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - java --version
      - $(aws ecr get-login --region us-west-2)
  build:
    commands:
      - mvn clean install
      - docker build -t  movieflix .
artifacts:
  files:
    - appspec.yml
    - files/*
    - scripts/*