#!/bin/bash
file="/opt/Dockerfile"

if [ -f $file ] ; then
    rm $file
fi

file="/opt/start_up.sh"

if [ -f $file ] ; then
    rm $file
fi

file="/opt/Movieflix-0.0.1-SNAPSHOT.jar"

if [ -f $file ] ; then
    rm $file
fi