version: 0.1
phases:
  build:
    commands:
      - mvn clean install
artifacts:
  files:
    - container/movieflix/appspec.yml
    - container/movieflix/files/*
    - container/movieflix/scripts/*
  discard-paths: yes